"use client";

import { FC, useCallback, useEffect, useState } from "react";
import { Unity, useUnityContext } from "react-unity-webgl";
import { UnityLoader } from "./unity-loader";
import useGameStore from "@/store/useGameStore";
import MainMenu from "../main-menu";

import MenuButton from "../main-menu/menu-button";
import LevelSelector from "../main-menu-level-selector";


interface UnityPlayerProps {
	test?: string;
}

const UnityPlayer: FC<UnityPlayerProps> = () => {

	const { setIsUnityLoaded, isMainMenuActive, setIsMainMenuActive, setIsLevelSelectorActive } = useGameStore();


	const {
		unityProvider,
		isLoaded,
		loadingProgression,
		addEventListener,
		removeEventListener,
		sendMessage
	} = useUnityContext({
		loaderUrl: "/game/Build/blitzer.loader.js",
		dataUrl: "/game/Build/blitzer.data",
		frameworkUrl: "/game/Build/blitzer.framework.js",
		codeUrl: "/game/Build/blitzer.wasm",
		companyName: "AWS Hackathon",
		productName: "Blitzer",
		productVersion: "1"
	});

	useEffect(() => {
		setIsUnityLoaded(isLoaded)
	}, [isLoaded]);






	const handleSetMainMain = useCallback(() => {
		setIsMainMenuActive(true)
	}, []);

	useEffect(() => {
		addEventListener("ActivateMainMenu", handleSetMainMain);
		return () => {
			removeEventListener("ActivateMainMenu", handleSetMainMain);
		};
	}, [addEventListener, removeEventListener, handleSetMainMain]);




	function handleClickSpawnEnemies() {
		setIsMainMenuActive(false);
		sendMessage("MainMenuManager", "StartGame");
	}


	return (
		<>
			<UnityLoader isLoaded={isLoaded} loadingProgression={loadingProgression} />
			<Unity id="game" unityProvider={unityProvider} className="fixed top-0 left-0 z-0 aspect-video w-full h-screen" />
			<MainMenu>
				<MenuButton onClick={handleClickSpawnEnemies} title="Standard" description="Play 3 levels and beat the final boss." />
				<MenuButton onClick={() => setIsLevelSelectorActive(true)} title="AI Levels" description="Play a level generated by AWS Bedrock." />
				<MenuButton onClick={handleClickSpawnEnemies} title="Boss Fight" description="Fight the boss in the final level." />
			</MainMenu>
			<LevelSelector />
		</>
	);
}

export default UnityPlayer;