import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { ClientProviderSession } from "@/providers/session-provider";

const saira = Saira({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${saira.className} antialiased`}
			>
				<ClientProviderSession>
					{children}
				</ClientProviderSession>
			</body>
		</html>
	);
}
